#cloud-config

package_update: true
package_upgrade: true
packages: ['snapd']

runcmd:
  - sudo ip addr add $FLOATINGIP dev eth0
  - sudo snap install microk8s --channel=1.19/stable --classic
  - sudo microk8s status --wait-ready
  - sudo microk8s enable dashboard dns registry ingress prometheus
